version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi_lab
    networks:
      - lab_network
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTP_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=SenhaForte123!
      - NIFI_JVM_OPTS="-Dorg.apache.nifi.bootstrap.sensitive.key=/opt/nifi/nifi-current/lib/postgresql-42.7.5.jar"
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_data:/opt/nifi/nifi-current/database_repository
      - nifi_flow:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_lib:/opt/nifi/nifi-current/lib

  postgres:
    image: postgres:latest
    container_name: postgres_lab
    networks:
      - lab_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=SenhaForte123!
      - POSTGRES_DB=my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: minio_lab
    networks:
      - lab_network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=SenhaForte123!
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_lab
    networks:
      - lab_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_lab
    depends_on:
      - zookeeper
    networks:
      - lab_network
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_lab:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_lab:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  # Permite a criação automática de tópicos
    volumes:
      - kafka_data:/var/lib/kafka/data  # Volume para persistência

  spark:
    image: bitnami/spark:latest
    container_name: spark_lab
    depends_on:
      - kafka
    networks:
      - lab_network
    environment:
      SPARK_MODE: master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark_output:/opt/spark/output

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui_lab
    depends_on:
      - kafka
    networks:
      - lab_network
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka_lab:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper_lab:2181
      
networks:
  lab_network:
    driver: bridge

volumes:
  postgres_data:
    external: true
  minio_data:
    external: true
  nifi_conf:
    external: true
  nifi_content:
    external: true
  nifi_data:
    external: true
  nifi_flow:
    external: true
  nifi_provenance:
    external: true
  nifi_lib:
    external: true
  spark_output:
    external: false
  kafka_data:
    external: true

