version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi_lab
    networks:
      - lab_network
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTP_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=SenhaForte123!
      - NIFI_JVM_OPTS="-Dorg.apache.nifi.bootstrap.sensitive.key=/opt/nifi/nifi-current/lib/postgresql-42.7.5.jar"

    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_data:/opt/nifi/nifi-current/database_repository
      - nifi_flow:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_lib:/opt/nifi/nifi-current/lib


  postgres:
    image: postgres:latest
    container_name: postgres_lab
    networks:
      - lab_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=SenhaForte123!
      - POSTGRES_DB=my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: minio_lab
    networks:
      - lab_network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=SenhaForte123!
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

networks:
  lab_network:
    driver: bridge

volumes:
  postgres_data:
    external: true
  minio_data:
    external: true
  nifi_conf:
    external: true
  nifi_content:
    external: true
  nifi_data:
    external: true
  nifi_flow:
    external: true
  nifi_provenance:
    external: true
  nifi_lib:
    external: true	


